# The different Materials to look for within the mine structure.
spawnPoint: SPONGE
mineCorner: POWERED_RAIL
sellNpc: WHITE_WOOL
upgradeMaterial: OBSIDIAN
quarryMaterial: SHULKER_BOX
mineDistance: 150
mineYLevel: 50
teleportDelay: 5
wallsGap: 1
giveMineOnFirstJoin: true
onlyReplaceAir: true
borderUpgrade: true
shouldWallsGoUp: false
locale: en_US
useAdventure: true
enableMenu: true

mineTypes:
  Test:
    file: minewithgap.schem
    resetTime: 5
    expand: 1
    resetPercentage: 50.0
    upgradeCost: 1.0
    upgradeCurrency: VAULT # Supported currencies: VAULT, ULTRAPRISONCORE (Coming soon, hopefully...)
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
    flags:
      block-break: true