# The different Materials to look for within the mine structure.
spawnPoint: SPONGE
mineCorner: POWERED_RAIL
sellNpc: WHITE_WOOL
upgradeMaterial: OBSIDIAN
mineDistance: 150
mineYLevel: 50
giveMineOnFirstJoin: true
onlyReplaceAir: true
locale: en_US

mineTypes:
  Test:
    file: minewithgap.schem
    resetTime: 5
    expand: 1
    resetPercentage: 50.0
    upgradeCost: 1.0
    upgradeCurrency: VAULT # Supported currencies: VAULT, ULTRAPRISONCORE (Coming soon, hopefully...)
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
    flags:
      block-break: true