# The different Materials to look for within the mine structure.
spawnPoint: "SPONGE"
mineCorner: "POWERED_RAIL"
sellNpc: "WOOL"
upgradeMaterial: "OBSIDIAN"
notifyForUpdates: true
mineDistance: 150

mineTypes:
  Test:
    file: minewithgap.schem
    resetTime: 5
    resetPercentage: 50.0
    materials:
      STONE: 0.9
      COBBLESTONE: 0.1
    flags:
      block-break: true