name: PrivateMines
main: me.untouchedodin0.privatemines.PrivateMines
version: 4.1.0
api-version: 1.13

depend:
  - FastAsyncWorldEdit
  - WorldGuard

softdepend:
  - AutoSell
  - UltraPrisonCore
  - Vault